export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"


export const LOADING_DOCTOR = "LOADING_DOCTOR"
export const ERROR_DOCTOR = "ERROR_DOCTOR"
export const GET_DOCTOR = "GET_DOCTOR" 
export const ADD_DOCTOR = "ADD_DOCTOR"
export const DELET_DOCTOR = "DELET_DOCTOR"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"